import { query } from "./postgres.js";

export const initializePostgres = async () => {
  try {
    await query(`
        CREATE TYPE user_role AS ENUM ('user', 'organizer');
        CREATE TYPE status AS ENUM ('open', 'closed', 'paused');
        CREATE TYPE sendStatus AS ENUM ('draft', 'sent');

        CREATE TABLE IF NOT EXISTS "users" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "first_name" VARCHAR(255) NOT NULL,
            "last_name" VARCHAR(255) NOT NULL,
            "email" VARCHAR(255) NOT NULL UNIQUE,
            "password_hash" VARCHAR(255) NOT NULL,
            "role" user_role NOT NULL DEFAULT 'user',
            "created_at" TIMESTAMPTZ DEFAULT now(),
            PRIMARY KEY("id")
        );


        CREATE TABLE IF NOT EXISTS "events" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "event" VARCHAR(255) NOT NULL,
            "start_date" TIMESTAMPTZ NOT NULL,
            "end_date" TIMESTAMPTZ NOT NULL,
            "attendee_count" INTEGER NOT NULL DEFAULT 0,
            "status" status NOT NULL DEFAULT 'open',
            "description" TEXT,
            location_id INTEGER REFERENCES locations(id) ON DELETE RESTRICT,
            PRIMARY KEY("id")
        );


        CREATE TABLE IF NOT EXISTS "locations" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "name" VARCHAR(255),
            "street_address" VARCHAR(255) NOT NULL,
            "city" VARCHAR(255) NOT NULL,
            "postcode" VARCHAR(255) NOT NULL,
            "additional_locator" VARCHAR(255),
            "country" VARCHAR(255),
            "archived" boolean DEFAULT false,
            PRIMARY KEY("id")
        );


        CREATE TABLE IF NOT EXISTS "notifications" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "sender_id" INTEGER NOT NULL,
            "event_id" INTEGER NOT NULL,
            "message" TEXT,
            "status" sendStatus DEFAULT 'draft',
            "created_at" TIMESTAMPTZ DEFAULT now(),
            "subject" TEXT NOT NULL,
            "sent_at" TIMESTAMPTZ,
            "deleted_by_organizer" boolean DEFAULT false;
            PRIMARY KEY("id")
            CHECK (status <> 'draft' OR deleted_by_organizer = false)
        );


        CREATE TABLE IF NOT EXISTS "event_users" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "event_id" INTEGER NOT NULL,
            "user_id" INTEGER NOT NULL,
            PRIMARY KEY("id")
        );


        CREATE TABLE IF NOT EXISTS "user_favorite_event" (
            "id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
            "user_id" INTEGER NOT NULL,
            "event_id" INTEGER NOT NULL,
            PRIMARY KEY("id")
        );

        CREATE TABLE IF NOT EXISTS event_organizers (
            event_id INTEGER UNIQUE NOT NULL,
            user_id INTEGER NOT NULL,
            PRIMARY KEY (event_id, user_id),
            FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS notification_users (
            notification_id INTEGER NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            is_read BOOLEAN DEFAULT FALSE,
            PRIMARY KEY (notification_id, user_id)
        );

        ALTER TABLE notifications
        ADD CONSTRAINT fk_notifications_sender
        FOREIGN KEY (sender_id)
        REFERENCES users(id)
        ON DELETE CASCADE;

        ALTER TABLE notifications
        ADD CONSTRAINT fk_notifications_event
        FOREIGN KEY (event_id)
        REFERENCES events(id)
        ON DELETE CASCADE;

        ALTER TABLE event_users
        ADD CONSTRAINT fk_event_users_event
        FOREIGN KEY (event_id) 
        REFERENCES events(id) 
        ON DELETE CASCADE;

        ALTER TABLE event_users
        ADD CONSTRAINT fk_event_users_user
        FOREIGN KEY (user_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE;

        ALTER TABLE user_favorite_event
        ADD CONSTRAINT fk_favorites_user
        FOREIGN KEY (user_id) 
        REFERENCES users(id) 
        ON DELETE CASCADE;

        ALTER TABLE user_favorite_event
        ADD CONSTRAINT fk_favorites_event
        FOREIGN KEY (event_id) 
        REFERENCES events(id) 
        ON DELETE CASCADE;

        ALTER TABLE event_location
        ADD CONSTRAINT fk_event_location_event
        FOREIGN KEY (event_id) 
        REFERENCES events(id)
        ON DELETE CASCADE;

        ALTER TABLE event_location
        ADD CONSTRAINT fk_event_location_location
        FOREIGN KEY (location_id) 
        REFERENCES locations(id);

        ALTER TABLE event_location
        ADD CONSTRAINT uq_event_location UNIQUE(event_id, location_id);

        ALTER TABLE event_users
        ADD CONSTRAINT uq_event_user UNIQUE(event_id, user_id);

        ALTER TABLE user_favorite_event
        ADD CONSTRAINT uq_user_favorite UNIQUE(user_id, event_id);

        CREATE INDEX idx_event_users_user_id ON event_users(user_id);
        CREATE INDEX idx_event_users_event_id ON event_users(event_id);

        CREATE INDEX idx_user_favorite_event_user_id ON user_favorite_event(user_id);
        CREATE INDEX idx_user_favorite_event_event_id ON user_favorite_event(event_id);

        CREATE INDEX idx_event_location_event_id ON event_location(event_id);
        CREATE INDEX idx_event_location_location_id ON event_location(location_id);
    `);
    console.log("PostgreSQL tables initialized successfully.");
  } catch (error: unknown) {
    console.error("PostgreSQL error:", error);
    throw error;
  }
};
